### ISSUE TITLE
craftingRequester:41: attempt to call nil

### ISSUE THREAD

**Issue by mcfunker** [sidoh/stockpile#1]
Greetings, 

Thanks so much for making this program it looks like just the thing I have been looking for!

I seem to get an error after I set an item. I run the program it allows me to choose what to set, I set one item (in this example sticky pistons to 40) then after a minute or so I get this error. craftingRequester:41: attempt to call nil 
When I attempt to start the program again with startup the error pops up again right after the menu is listed and then crashes the program. 

Any idea?

Thanks so much!

![image](https://cloud.githubusercontent.com/assets/16978055/12697995/6ba13f78-c75f-11e5-913c-957bd71cbd59.png)

**Comment by sidoh** [comment]
Glad it's what you're looking for! Hope it ends up being useful.

The offending line is:

```
aeInterface.requestCrafting(stockedItem.item, stockCount)
```

So it seems like either `aeInterface` or `stockedItem` is nil. You didn't happen to move or replace the AE interface, did you? I don't see a way for alternative option (`stockedItem` being nil) to be the case offhand.

**Comment by mcfunker** [comment]
This occurs on a fresh implementation. It seems like when it starts to craft is when it runs in the item being nil. I will do some more digging and see if there is any other situation this occurs in.

**Comment by Letouane** [comment]
Hi Sidoh, thank you for this promising program !
I have the same problem so as I don't know if I have to create another ticket I'll start posting here...
I'm a complete noob at ComputerCraft so I'll try to explain what I did...
In my world (minecraft 1.7.10 / FTB Infinity Evolved 2.6.0 : ComputerCraft 1.75 ; AE2 RV3 beta 6) I put in that order :

1. ME Smart cable to a dense smart cable
2. An interface (a cubic one or a flat one, did both) at the end of the smart cable
3. An advanced computer which is connected by his back side to the interface
4. I launched the install of stockpile
5. Added "Redstone" or "Iron Ingot" to the list with a threshold of 100 (tried 1000 too) which are verified by the program in order to be sure that it's not other kind of iron ingot like "refined iron ingot"
6.  The program crashes with the message "craftingRequester:41: attempt to call nil"

As I'm not sure about what to do, I tried :

1. adding a crafting card to the interface and setup the program : same error
2. break the computer and set it up again
3. to figure out what am I doing wrong by checking the code

I'm sure I made a nooby mistake and forgot to add an important element between my AE system and the computer.

Can you please help me a bit ?

**Comment by sidoh** [comment]
I've not played in quite a while, so I'm probably not going to be much help. :(

I think the AE interface needs to be on the back side of the computer:

https://github.com/sidoh/stockpile/blob/master/stockpile/craftingRequester#L4

This is the only reason I can think of that this would be nil if an interface is attached.

**Comment by Letouane** [comment]
Yep I figured out that the interface had to be there as I checked the code and put the interface at the back.
https://imgur.com/a/vcdflB2

By the way, I also tried to change it to bottom and change the position of the elements but the error remains the same :-(

**Comment by Letouane** [comment]
Solved it ! If anyone faces the problem :
I used a cubic interface (not a flat one) and wrenched it to have the arrow at the top facing to the computer :)
Many thanks Sidoh for th program and your interest to my question.

**Comment by sidoh** [comment]
Excellent!  Glad you got it working.

If you wouldn't mind, could you upload some screenshots of how you have it set up?  I can add them to the README.

**Comment by Letouane** [comment]
By the way, I'll be glad to provide screenshots in order to help other user setting up your program :)

**Comment by sidoh** [comment]
That'd be very helpful.  Just drop them here, or open a PR if you prefer.

**Comment by Letouane** [comment]
I'll post them here in a few hours as I'm at work.

**Comment by Letouane** [comment]
![Physical setup](https://user-images.githubusercontent.com/32341208/42074571-90a266b2-7b08-11e8-87d8-7e22fefa457b.png)

![Nothing in the interface GUI](https://user-images.githubusercontent.com/32341208/42074569-90743a6c-7b08-11e8-8385-6e8e79b75e0b.png)

![The soft works great](https://user-images.githubusercontent.com/32341208/42074568-9041dfa4-7b08-11e8-8b72-f89218735cbc.png)

**Comment by sidoh** [comment]
Added your screenshots to the README (with an attribution).  Thank you!
