### ISSUE TITLE
Download from pastebin is failing

### ISSUE THREAD

**Issue by Rasmun** [sidoh/stockpile#5]
I used "pastebin run 1WqtKyB6" and I am getting several failures.  It looks like several of the pastebins have expired.

**Comment by sidoh** [comment]
Mmm.. bummer. I think Pastebin's API isn't cooperating. Should probably take this down for now. Thanks for raising.

**Comment by sidoh** [comment]
Can you try again with the updated pastebin?

```
pastebin run XCUXeQL7
```

I think the script I wrote to upload to pastebin had files that needed solved CAPTCHAs.

**Comment by Rasmun** [comment]
I tried again, but it still failed.  I see each of the bins it points to exist, so not sure why its failing now.

**Comment by Rasmun** [comment]
I tried on another server.  The first script says it's a success, but the other 6 gets say Failed and at the end it says "no such program".  However, if I manually pastbin get the individual pastbins that I can see in XCUXeQL7, that works.  For some reason it just doesn't seem to like the get statements in that paste bin.  Note this is CraftOS 1.7 in the latest FTB Infinity Evolved for minecraft 1.7.10

**Comment by sidoh** [comment]
Nice, thanks for trying it on another server.

I was having trouble on my server as well. The problem seems to be pastebin is returning the HTML for one of its pages for at least one of the scripts instead of the paste itself.

I assume this is because pastebin doesn't like that the script I used to upload the program uploaded everything in a short period of time. Really not happy with pastebin. :(

I saw someone had a pastebin script that checked out projects directly from github. I think I might be able to leverage that to get a general installer script working that I don't need to update. I'll try to do that this evening.

**Comment by Rasmun** [comment]
Cool.  I'll be happy to test it.  Thanks for the help with this.  Great script btw.  It's very helpful so far!

**Comment by sidoh** [comment]
Can you try

```
pastebin install KghxhDha
```

?

Verified on my server a few times that it works.

**Comment by Rasmun** [comment]
Nope, that didn't work.  It does not seem to like the key word **install**.  The only paste bin commands it wants to accept are **get**, **put**, and **run**.  

I went ahead and tried the following and it worked!

`pastebin run KghxhDha`

Thank you!

**Comment by sidoh** [comment]
Oops, sorry. I meant to type `pastebin run`. I was falling asleep :)

Glad that worked! I'll close this. Let me know if you notice anything else.

Thanks for your help.

**Comment by Rasmun** [comment]
I did find one issue with this.  I ran it on my main computer that had a bit older version of your program and it deleted all the stock items I had already setup.  :(  It would be nice if it updated the program files without deleting the files that contain existing stocked items.

**Comment by sidoh** [comment]
Ouch. Sorry about that. :(

Non-destructive updates should be doable. Opened #6 for that.
